version: '2.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    hostname: redis

  redis-client:
    image: "rediscommander/redis-commander:latest"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  elasticmq:
    image: "s12v/elasticmq:latest"
    ports:
      - "9324:9324"
    hostname: sqs
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27016:27017'
    environment:
      MONGO_INITDB_DATABASE: Bill_Management
    hostname: mongo